"""Writes docs/laptime-model.md from data/model.json."""
import json, os
MPH = 2.23694
NAMES = dict(oblivion='Oblivion', crook='Crook', finelady='Fine Lady', christmas='Christmas', kink='Left kink', inkermans='Inkermans', ashby='Ashby', parker='Parker',
             chapmans='Chapmans', chap2='Chapmans exit bend', boot1='The Boot, left', boot2='The Boot, right', boot3='The Boot, second right', chic1='Chicane', pitbend='Pit Bend',
             inkhair='Inkermans hairpin', zulu1='Zulu 1', zulu2='Zulu 2', zulu3='Zulu 3')
LV = {1: 'flat', 2: 'lift or coast', 3: 'light brake', 4: 'firm brake', 5: 'full brake'}


def write(out, path):
    L = out['layouts']; P = out['params']; K = out['karts']; B = out.get('benchmark', {})
    o = []
    o.append('# What the physics says: fastest possible laps at Whilton Mill\n')
    o.append('Generated by `model/laptime.py`. Every number here is a model output built on estimates; nothing was measured at the circuit. Read the caveats at the end before quoting any of it.\n')
    o.append('## How the model works\n')
    o.append('- The track is the traced centreline in `data/data.json`, resampled to 1 m, on the 1200 m scale. The usable width is the track width minus the kart minus a margin, so the line may run out to ' + f'{P["track_width"] / 2 - P["kart_width"] / 2 - P["edge_margin"]:.1f}' + ' m either side of the centreline.')
    o.append('- Heights are a smooth curve through values set at each corner from the written guides (the climb from Crook to Christmas, the drop through the kink and Inkermans to Ashby, the hairpin and Zulu running down the hill). The height of the hill is a parameter, ' + f'{P["hill"]:.0f}' + ' m by default, and is swept.')
    o.append('- The kart is a point mass with a friction ellipse: cornering grip sets the speed the tyres allow through each metre, the engine and the driven rear axle set how hard it can accelerate, the rear-only brakes and the slope set how hard it can slow. Drag and rolling resistance act throughout, gravity along the slope adds or takes away.')
    o.append('- For any given line the fastest speed profile is found by a forward pass (acceleration) and a backward pass (braking) on the closed lap; the lower of the two at each point is what a perfect driver could do.')
    o.append('- The racing line is a smooth curve of sideways offsets at control points every ' + f'{P["ctrl_spacing"]:.0f}' + ' m, kept inside the track. The lap time is minimised, then the search restarts from the best line with a random shake, again and again, until five rounds in a row bring no gain. The round-by-round record is in `data/model.json`.\n')
    o.append('## The karts\n')
    o.append('| | Hire kart | Race kart |\n|---|---|---|')
    for k, lab in (('mass', 'Mass with driver, kg'), ('power_kw', 'Engine power, kW'), ('drive_eff', 'Driveline efficiency'), ('v_top', 'Top speed, m/s'), ('cda', 'Drag area CdA, m2'), ('crr', 'Rolling resistance'), ('mu_y', 'Cornering grip, g'), ('mu_x', 'Traction, g'), ('mu_b', 'Braking, g')):
        o.append(f'| {lab} | {K["hire"][k]} | {K["race"][k]} |')
    o.append('\nThe hire kart is the BirelART N35 with a Honda GX390: 140 to 150 kg, 13 bhp at 3600 rpm and 55 mph are the maker\'s figures; the grip, traction, braking, drag and rolling figures are estimates for a heavy kart on hard tyres and a low-grip surface. The race kart is a two-stroke Club100 or Rotax style kart, all estimates. In the wet the model uses cornering grip ' + f'{out["wet"]["mu_y"]}' + ' g for the hire kart and scales the race kart the same way.\n')
    o.append('## Results\n')
    o.append('| Layout | Kart | Dry lap | Centreline lap | Gained by the line | Average speed | Top speed | Flat out | Wet lap | Rounds |\n|---|---|---|---|---|---|---|---|---|---|')
    for key, lay in L.items():
        for kart in ('hire', 'race'):
            r = lay['karts'].get(kart); w = lay['karts'].get(kart + '_w')
            if not r: continue
            o.append(f'| {lay["name"]} | {kart} | {r["lap"]:.2f} s | {r["centreline_lap"]:.2f} s | {r["gain_from_line"]:.2f} s | {r["v_mean"]} mph | {r["v_max"]} mph | {r["flat_share"] * 100:.0f}% | {w["lap"]:.2f} s | {r["rounds"]} |' if w else f'| {lay["name"]} | {kart} | {r["lap"]:.2f} s | {r["centreline_lap"]:.2f} s | {r["gain_from_line"]:.2f} s | {r["v_mean"]} mph | {r["v_max"]} mph | {r["flat_share"] * 100:.0f}% | | {r["rounds"]} |')
    if B:
        o.append(f'\nBenchmark: a {B["hire_record_s"]:.2f} s hire-kart lap on the International before the chicane ({B["hire_record_note"]}, {B["hire_record_url"]}). See the calibration below for what that time needs.\n')
    o.append('## Corner by corner, hire kart, dry\n')
    for key, lay in L.items():
        r = lay['karts'].get('hire')
        if not r: continue
        o.append(f'### {lay["name"]}\n')
        o.append('| Corner | Speed when the throttle comes off | Slowest | Off throttle, before turn-in | Brakes on, before turn-in | Peak braking | What the feet do |\n|---|---|---|---|---|---|---|')
        fmt = lambda bb: 'none' if bb is None else (str(bb) + ' m' if bb >= 0 else str(-bb) + ' m after turn-in')
        for c in D_ORDER(key):
            x = r['corners'].get(c)
            if not x: continue
            o.append(f'| {NAMES.get(c, c)} | {x["v_in"]} mph | {x["v_min"]} mph | {fmt(x.get("lift_before_turnin_m"))} | {fmt(x["brake_before_turnin_m"])} | {x["peak_decel_g"]} g | {LV[x["level"]]} |')
        o.append('')
    seeds = {k: v.get('seeds', {}).get('hire') for k, v in L.items() if v.get('seeds', {}).get('hire')}
    if seeds:
        o.append('## Is it the best, or just a good one?\n')
        o.append('Every hire-kart layout was searched again from three more random seeds with a stronger shake schedule (every third round a 1.2 m shake, eight idle rounds to stop). The spread between seeds is how much a single search can be off its best.\n')
        o.append('| Layout | First run | Seeds | Spread | Kept |\n|---|---|---|---|---|')
        for k, sd in seeds.items():
            o.append(f'| {L[k]["name"]} | {sd["first_run"]:.3f} s | ' + ', '.join(f'{v:.3f}' for v in sd['laps'].values()) + f' s | {sd["spread"]:.3f} s | {L[k]["karts"]["hire"]["lap"]:.3f} s |')
        o.append('')
    r0 = L.get('intl_c', {}).get('karts', {}).get('hire')
    if r0:
        o.append('## Over and over: how the search converged\n')
        o.append('International with the chicane, hire kart, dry. Each round runs a full L-BFGS-B minimisation from the best line so far, shaken by a random amount that shrinks round by round; the search stops after five rounds without a gain.\n')
        o.append('| Round | Start | Lap found | Best so far |\n|---|---|---|---|')
        for hrow in r0['hist']:
            o.append(f'| {hrow["round"]} | {hrow["start"]} | {hrow["lap"]:.3f} s | {hrow["best"]:.3f} s |')
        o.append('')
    S = out.get('sweeps', {})
    if S:
        o.append('## What nobody has measured, and how much it matters\n')
        o.append('All on the International without the chicane, hire kart, dry. ' + out.get('sweeps_note', 'Shorter optimisation runs than the main results, so differences under about half a second are search noise, not physics.') + '\n')
        o.append('| Case | Lap | Average speed | Christmas slowest | Ashby slowest |\n|---|---|---|---|---|')
        for name, v in S.items():
            o.append(f'| {name.replace("_", " ")} | {v["lap"]:.2f} s | {v["v_mean"]} mph | {v["christmas"]["v_min"] if v.get("christmas") else ""} mph | {v["ashby"]["v_min"] if v.get("ashby") else ""} mph |')
        o.append('\nThe hill cases show how much the slope changes the brake points at Christmas (uphill) and Ashby (downhill). The grip cases scale cornering, traction and braking grip together. The length case shrinks the whole map to the 1054 m the 2025 regulations state. The calibration rows show which combination of length and grip would be needed to reproduce the record lap.\n')
    o.append('## Caveats\n')
    o.append('- No height, width or length of the circuit has been measured for this model. The hill is a guess from words like "up the hill" and "downhill", the width is the usual kart-circuit width, and the length is disputed between 1054 m and 1200 m.')
    o.append('- The kart\'s grip, traction and braking are estimates. A real hire kart also has a driver-dependent clutch, tyre temperature and a rev limiter the model does not know about.')
    o.append('- A point-mass model has no yaw dynamics, no load transfer beyond what the grip figures assume, no kerbs and no traffic. It shows where time is won and lost and roughly where to brake; it does not know how the kart feels.')
    o.append('- Because of all this, the relative results (which corners cost most, how much the line is worth, how the hill moves the brake points) are worth more than the absolute lap time.')
    open(path, 'w', encoding='utf-8').write('\n'.join(o) + '\n')


def D_ORDER(key):
    import json, os
    d = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'data', 'data.json')))
    return d['layouts'][key]['order']
