"""Writes docs/model-vs-guide.md: for every layout, chicane setting and driver level, does the physics model agree with the
guide at each corner (the pedal, the brake point, the line at approach, apex and exit)? Runs the app's own modelAgreement()
in a headless browser so the report and the cards can never disagree. Run after build/build.py."""
from playwright.sync_api import sync_playwright
import os, datetime
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL = 'file://' + os.path.join(ROOT, 'dist', 'index.html')
JS = """() => { const W = window.__wm, out = []; for (const lay of ['intl', 'nat']) for (const chic of [true, false]) for (const prof of ['novice', 'inter', 'expert']) {
  Object.assign(W.st, { layout: lay, chic, wet: false, profile: prof }); W.setTab('corners');
  const names = [...document.querySelectorAll('#acc details .nm')].map(e => e.textContent), rows = [];
  [...document.querySelectorAll('#acc details')].forEach((d, i) => { const t = d.textContent, m = t.match(/Model against the guide(.*?)(Worth knowing|$)/), md = t.match(/What the model does(.*?)A point-mass/); rows.push({ name: names[i], text: m ? m[1].replace(/The model drives a point-mass.*$/, '').trim() : 'no model', model: md ? md[1].trim() : '' }); });
  out.push({ lay, chic, prof, rows }); } Object.assign(W.st, { layout: 'intl', chic: true, profile: 'novice' }); return out; }"""
with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(); pg.goto(URL); pg.wait_for_timeout(500); res = pg.evaluate(JS); b.close()
lines = ['# The model against the guide, corner by corner', '',
         f'Generated by `tools/model_vs_guide.py` on {datetime.date.today().isoformat()} from the app\'s own comparison (`modelAgreement` in src/app.src.html), so the cards and this page say the same thing.', '',
         'For each corner: the pedal (flat, lift or brake) the guide gives the driver level (novice, intermediate or advanced) against the pedal the model\'s hire kart uses at its limit; where the model starts braking against where the guide\'s painted zone starts; and which side of the track each is on at the approach (where the braking starts, or 20 m before turn-in), the apex and 10 m after the exit. "Agrees" means all three match within the tolerances (pedal class the same, brake point within 10 m, sides the same or within 1.5 m).', '',
         'The model is a point mass at its grip limit on an estimated hill, calibrated to one measured hire lap; the guides are written for a person. Where they differ, the guide is the day-one plan and the model shows where the time is. A model that brakes later than the guide\'s zone is expected: the zones carry margin. A model that brakes where the guide says lift or flat says that corner is at the edge for a hire kart at the limit, and a novice should take the guide\'s word first.', '']
total = ok = 0
for blk in res:
    title = ('International' if blk['lay'] == 'intl' else 'National') + (' with the chicane' if blk['chic'] else ' without the chicane') + ', ' + {'novice': 'novice', 'inter': 'intermediate', 'expert': 'advanced'}[blk['prof']]
    lines += [f'## {title}', '', '| Corner | Model, hire kart | Against the guide |', '|---|---|---|']
    for r in blk['rows']:
        total += 1; ok += r['text'].startswith('Agrees')
        lines.append(f"| {r['name']} | {r['model']} | {r['text']} |")
    lines.append('')
lines.insert(4, f'Across every layout, chicane setting and driver level: {ok} of {total} corner readings agree on all three counts; the rest differ on at least one, and the table says which.')
lines.insert(5, '')
open(os.path.join(ROOT, 'docs', 'model-vs-guide.md'), 'w').write('\n'.join(lines))
print('wrote docs/model-vs-guide.md:', ok, 'of', total, 'agree')
